# This is a basic workflow to help you get started with Actions

name: AzWeeklyWorkflow

# Controls when the workflow will run
on:
  pull_request:
    types:
      - closed
      
permissions:
      id-token: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: azure/login@v1
      with:
          client-id: ${{ secrets.DS_CLIENT_ID }}
          tenant-id: ${{ secrets.DS_TENANT_ID }}
          subscription-id: ${{ secrets.DS_SUBSCRIPTION_ID }}


