# This is a basic workflow to help you get started with Actions

name: AzWeeklyWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.DS_CLIENT_ID }}","clientSecret":"${{ secrets.DS_CLIENT_SECRET }}","subscriptionId":"${{ secrets.DS_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.DS_TENANT_ID }}"}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.42.0
        inlineScript: |
         az config set extension.use_dynamic_install=yes_without_prompt
         az datafactory pipeline create-run --factory-name ADFGithub01 --name WaitPipeline --resource-group GithubActionsDemo00
