# This is a basic workflow to help you get started with Actions

name: demo00

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
    pull_request_target:
     types:
      - closed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.DS_CLIENT_ID }}","clientSecret":"${{ secrets.DS_CLIENT_SECRET }}","subscriptionId":"${{ secrets.DS_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.DS_TENANT_ID }}"}'
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.41.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az datafactory pipeline create-run --factory-name "ADFGithub00" --name "WaitPipeline" --resource-group "GithubActionsDemo00"
