# This is a basic workflow to help you get started with Actions

name: sample flow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.DS_CLIENT_ID }}","clientSecret":"${{ secrets.DS_CLIENT_SECRET }}","subscriptionId":"${{ secrets.DS_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.DS_TENANT_ID }}"}'

    
